### ISSUE TITLE
None

### ISSUE THREAD

**Issue by uis246** [BlayzerQ/VKBot#2]

**Comment by ghost** [comment]
@uis246 Модуль - Сложный узел, выполняющий самостоятельную функцию в техническом устройстве, а также вообще отделяемая, относительно самостоятельная часть какой-н. системы, организации.
Т.е. модуль не обязательно отделяемый должен быть :)

**Comment by uis246** [comment]
А я пытаюсь сделать отделяемый. https://github.com/uis246/VKBot
Там пытаюсь сделать на основе bukkit(minecraft server api)
